chore(nodejs): update client ref docs link in metadata
googleapis/cloud-trace-nodejs pull request #1371
Opened 2021-08-03 19:42 UTC by fhinkel

2021-08-04 13:56 UTC, gkf commented on README.md
> +[client-docs]: https://cloud.google.com/nodejs/docs/reference/trace-agent/latest
The new link is broken for me?

2021-08-04 19:58 UTC, alexander-fenster approved these changes

2021-08-19 18:07 UTC, JustinBeckwith requested changes
this 404s

2021-08-19 18:14 UTC, fhinkel commented
Let me find out why the trace docs didn't get published

2021-08-20 23:38 UTC, fhinkel commented
I kicked off the docs job, links is valid now.

2021-08-21 14:37 UTC, JustinBeckwith approved these changes

2021-08-21 14:37 UTC, merged